### ISSUE TITLE
newInstance is null

### ISSUE THREAD

**Issue by MartinKayJr** [dingyi222666/GroovyInAndroid#1]
newInstance的时候空指针了咋回事

**Comment by MartinKayJr** [comment]
```
            Binding binding = new Binding();
            binding.setVariable("view", view);
            binding.setVariable("context", context);
            // 回调变量
            binding.setVariable("callback", "");
            DynamicGrooidClassLoader classLoader = new DynamicGrooidClassLoader(context.getClassLoader(), null, false);

            String format = String.format("%s%d.png", key, Long.valueOf(System.currentTimeMillis()));
            ContextWrapper contextWrapper = new ContextWrapper(context);
            File directory = contextWrapper.getDir("my_groovy", Context.MODE_PRIVATE);

            GroovyCodeSource groovyCodeSource = new GroovyCodeSource(expValue, format, directory.getAbsolutePath());
            Class<groovy.lang.Script> scriptClass = classLoader.parseClass(groovyCodeSource);
            Script script = scriptClass.newInstance();
            script.setBinding(binding);
            Object run = script.run();
            Object callback = binding.getVariable("callback");
            if (callback instanceof String) {
                result = (String) callback;
            }

```

**Comment by dingyi222666** [comment]
想问一下,你在那个 android 版本下使用,出现了此错误?

**Comment by MartinKayJr** [comment]
好像是Android12来着

**Comment by dingyi222666** [comment]
你那个 expValue 的值是啥呢?

我可能过一两周后才有时间去复现，可以的话先看看你能不能自行解决(提 pr)

**Comment by MartinKayJr** [comment]
2024-03-26 09:15:37.498  3991-3991  .tencent.wewor          com.tencent.wework                   W  Unsupported class loader
2024-03-26 09:15:37.498  3991-3991  .tencent.wewor          com.tencent.wework                   E  Could not create class loader context for /data/user/0/com.tencent.wework/oat/arm64/Anonymous-DexFile@1906433816.vdex
2024-03-26 09:15:37.498  3991-3991  DexCompiler             com.tencent.wework                   D  compileAndLoadClassByteCode: compile to memory

**Comment by MartinKayJr** [comment]
日志是这个问题

**Comment by MartinKayJr** [comment]
当我使用context.getApplicationContext().getClassLoader()后出现了新的问题，

```
 Invalid ID 0x00000000.
 java.io.IOException: Stream closed
 	at java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:161)
 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:248)
 	at java.io.BufferedInputStream.read1(BufferedInputStream.java:288)
 	at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
 	at java.io.DataInputStream.readFully(DataInputStream.java:198)
 	at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:341)
 	at java.io.DataInputStream.readUTF(DataInputStream.java:586)
 	at java.io.DataInputStream.readUTF(DataInputStream.java:561)
 	at org.codehaus.groovy.reflection.GeneratedMetaMethod$DgmMethodRecord.loadDgmInfo(GeneratedMetaMethod.java:194)
 	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerMethods(MetaClassRegistryImpl.java:199)
 	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:108)
 	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:86)
 	at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:37)
 	at groovy.lang.GroovySystem.getMetaClassRegistry(GroovySystem.java:71)
 	at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:88)
 	at org.codehaus.groovy.runtime.InvokerHelper.getMetaClass(InvokerHelper.java:987)
 	at groovy.lang.GroovyObjectSupport.getDefaultMetaClass(GroovyObjectSupport.java:46)
 	at groovy.lang.GroovyObjectSupport.<init>(GroovyObjectSupport.java:32)
 	at groovy.lang.Binding.<init>(Binding.java:33)
 	at cn.martinkay.blackspider.reflection.abstractor.impl.ComponentInfoDialog.parseExpressions(ComponentInfoDialog.java:107)
 	at cn.martinkay.blackspider.reflection.abstractor.impl.ComponentInfoDialog.addContent(ComponentInfoDialog.java:86)
 	at cn.martinkay.blackspider.reflection.abstractor.CustomDialog.loadView(CustomDialog.java:71)
 	at cn.martinkay.blackspider.reflection.abstractor.BaseDialog.init(BaseDialog.java:75)
 	at cn.martinkay.blackspider.reflection.abstractor.BaseDialog.<init>(BaseDialog.java:62)
 	at cn.martinkay.blackspider.reflection.abstractor.BaseDialog.<init>(BaseDialog.java:45)
 	at cn.martinkay.blackspider.reflection.abstractor.CustomDialog.<init>(CustomDialog.java:31)
 	at cn.martinkay.blackspider.reflection.abstractor.decorator.CustomHeaderDialogDecorator.<init>(CustomHeaderDialogDecorator.java:20)
 	at cn.martinkay.blackspider.reflection.abstractor.impl.ComponentInfoDialog.<init>(ComponentInfoDialog.java:25)
 	at cn.martinkay.blackspider.widget.dialog.VariableDialogMenu.onClick(VariableDialogMenu.java:283)
 	at android.view.View.performClick(View.java:7441)
 	at android.view.View.performClickInternal(View.java:7418)
 	at android.view.View.access$3700(View.java:835)
 	at android.view.View$PerformClick.run(View.java:28676)
 	at android.os.Handler.handleCallback(Handler.java:938)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loopOnce(Looper.java:201)
 	at android.os.Looper.loop(Looper.java:288)
 	at android.app.ActivityThread.main(ActivityThread.java:7842)

2024-03-26 09:24:01.193  8576-8576  System.err              com.tencent.wework                   W  	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
 compileAndLoadClassByteCode: compile to memory
```

**Comment by dingyi222666** [comment]
你用 this.getClass().getClassLoader() 有这样的问题吗？

**Comment by dingyi222666** [comment]
看起来问题出在 class

**Comment by MartinKayJr** [comment]
![image](https://github.com/dingyi222666/GroovyInAndroid/assets/37266273/228a425c-e105-44c4-935b-917ac0d0dbc6)

**Comment by MartinKayJr** [comment]
你看看这个

**Comment by MartinKayJr** [comment]
和上面的异常是一样的
